[versions]
gradle = "9.7.1"
java = "26"
paper = "26.2.build.116-stable"
paperweight = "2.0.0-beta.21"
run-paper = "3.1.0"
gson = "2.14.0"
guice = "7.0.0"
hibernate = "7.2.24.Final"
flyway = "13.3.0"
postgresql = "42.7.12"
aws-sdk = "2.54.2"
zstd-jni = "1.5.7-15"
sshj = "0.40.0"
hikari = "7.0.2"
junit = "5.11.4"
junit-platform = "1.11.4"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
hibernate-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
aws-s3 = { module = "software.amazon.awssdk:s3", version.ref = "aws-sdk" }
sshj = { module = "com.hierynomus:sshj", version.ref = "sshj" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstd-jni" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
