name: ReplayExample
version: '${frameworkVersion}'
main: dev.voldechse.replayframework.example.ReplayExamplePlugin
api-version: '26.2'
dependencies:
  server:
    - name: ReplayFramework
      required: true
      load: BEFORE
      join-classpath: true
